import DS from 'ember-data';
import Ember from 'ember';

export default DS.Model.extend({
  acronym: DS.attr(),
  armGroups: DS.attr(),
  biospecDescr: DS.attr(),
  biospecRetention: DS.attr(),
  briefSummary: DS.attr(),
  briefTitle: DS.attr(),
  clinicalResults: DS.attr(),
  completionDateActual: DS.attr(),
  completionDateAnticipated: DS.attr(),
  conditionBrowse: DS.attr(),
  conditions: DS.attr(),
  detailedDescription: DS.attr(),
  downloadDate: DS.attr(),
  eligibility: DS.attr(),
  enrollmentActual: DS.attr(),
  enrollmentAnticipated: DS.attr(),
  firstreceivedDate: DS.attr(),
  hasExpandedAccess: DS.attr(),
  interventionBrowse: DS.attr(),
  interventions: DS.attr(),
  isFdaRegulated: DS.attr(),
  isSection801: DS.attr(),
  keywords: DS.attr(),
  lastchangedDate: DS.attr(),
  links: DS.attr(),
  linkText: DS.attr(),
  locationCountries: DS.attr(),
  locations: DS.attr(),
  nctAliases: DS.attr(),
  nctId: DS.attr(),
  numberOfArms: DS.attr(),
  numberOfGroups: DS.attr(),
  officialTitle: DS.attr(),
  orgStudyId: DS.attr(),
  otherOutcomes: DS.attr(),
  overallContact: DS.attr(),
  overallContactBackup: DS.attr(),
  overallOfficials: DS.attr(),
  overallStatus: DS.attr(),
  oversightInfo: DS.attr(),
  phase: DS.attr(),
  primaryCompletionDateActual: DS.attr(),
  primaryCompletionDateAnticipated: DS.attr(),
  primaryOutcomes: DS.attr(),
  references: DS.attr(),
  removedCountries: DS.attr(),
  responsibleParty: DS.attr(),
  resultsReferences: DS.attr(),
  secondaryIds: DS.attr(),
  secondaryOutcomes: DS.attr(),
  source: DS.attr(),
  sponsors: DS.attr(),
  startDate: DS.attr(),
  studyDesign: DS.attr(),
  studyType: DS.attr(),
  targetDuration: DS.attr(),
  url: DS.attr(),
  verificationDate: DS.attr(),
  whyStopped: DS.attr(),
  collection: DS.belongsTo('collection'),
  history: DS.hasMany('history', {async: true})
});
